### ISSUE TITLE
疑似镜像挂了

### ISSUE THREAD

**Issue by twdjlzl** [sMythicalBird/ZenlessZoneZero-Auto#135]
![image](https://github.com/user-attachments/assets/7fc2786c-4ea9-4581-85ee-8d3d67279778)
尝试两台不同机器 尝试直接安装但是还是通不过

**Comment by twdjlzl** [comment]
ERROR: HTTP error 404 while getting https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/pyyaml/) (requires-python:>=3.8)
ERROR: Could not install requirement pyyaml from https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from -r requirements-dml.txt (line 19)) because of HTTP error 404 Client Error: Not Found for url: https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/pyyaml/) (requires-python:>=3.8)

**Comment by sMythicalBird** [comment]
镜像不可能挂，是你那边ip有问题

**Comment by rendingGit** [comment]
我这边也是这个问题，不管是挂梯子，不挂梯子都是一样的问题

**Comment by rendingGit** [comment]
ERROR: HTTP error 404 while getting https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/pyyaml/) (requires-python:>=3.8)
ERROR: Could not install requirement pyyaml from https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from -r requirements-dml.txt (line 19)) because of HTTP error 404 Client Error: Not Found for url: https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl for URL https://pypi.tuna.tsinghua.edu.cn/packages/b5/84/0fa4b06f6d6c958d207620fc60005e241ecedceee58931bb20138e1e5776/PyYAML-6.0.2-cp310-cp310-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/pyyaml/) (requires-python:>=3.8)

**Comment by sMythicalBird** [comment]
ip问题

**Comment by rendingGit** [comment]
> ip问题

我尝试了四川的IP，北京的IP，杭州的IP，手机的热点，结果都是404

**Comment by twdjlzl** [comment]
> 我这边也是这个问题，不管是挂梯子，不挂梯子都是一样的问题

老哥你在海外吗？

**Comment by rendingGit** [comment]
> > 我这边也是这个问题，不管是挂梯子，不挂梯子都是一样的问题
> 
> 老哥你在海外吗？

国内，目前在四川，找人外地的朋友试了一下脚本，也是这个问题

**Comment by twdjlzl** [comment]
> ip问题

我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去

**Comment by rendingGit** [comment]
> > ip问题
> 
> 我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去

修改根目录下面的requirements-dml.txt这个文件试试，里面加上指定的版本号可以的话和我说一下版本号

**Comment by twdjlzl** [comment]
> > > ip问题
> > 
> > 
> > 我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去
> 
> 修改根目录下面的requirements-dml.txt这个文件试试，里面加上指定的版本号可以的话和我说一下版本号

我重新下了一遍也没问题 感觉就是网站那个版本的文件挂了

**Comment by rendingGit** [comment]
> > > > ip问题
> > > 
> > > 
> > > 我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去
> > 
> > 
> > 修改根目录下面的requirements-dml.txt这个文件试试，里面加上指定的版本号可以的话和我说一下版本号
> 
> 我重新下了一遍也没问题 感觉就是网站那个版本的文件挂了

你那边可以成功运行了吗？

**Comment by rendingGit** [comment]
> > > > ip问题
> > > 
> > > 
> > > 我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去
> > 
> > 
> > 修改根目录下面的requirements-dml.txt这个文件试试，里面加上指定的版本号可以的话和我说一下版本号
> 
> 我重新下了一遍也没问题 感觉就是网站那个版本的文件挂了

我将源换为阿里云的，使用手动安装的方式脚本已经可以正常运行了

**Comment by twdjlzl** [comment]
> > > > > ip问题
> > > > 
> > > > 
> > > > 我尝试了PyYAML和rapidfuzz上一个版本 都能直接下载 但是我不会修改exe可以没办法绕过去
> > > 
> > > 
> > > 修改根目录下面的requirements-dml.txt这个文件试试，里面加上指定的版本号可以的话和我说一下版本号
> > 
> > 
> > 我重新下了一遍也没问题 感觉就是网站那个版本的文件挂了
> 
> 我将源换为阿里云的，使用手动安装的方式脚本已经可以正常运行了

我安装依赖没问题 两个文件换成上个版本的就没问题了 现在正在下载运行的文件 我待会也试试看手动安装下
